## Práctica

Puedes utilizar este notebook para analisar el dataset propuesto

In [2]:
# PASO 1: IMPORTO LIBRERIAS
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# PASO 2: CARGAR DATOS
# ruta para traer los dtos
ruta = r"C:\Users\aleva\OneDrive\Escritorio\Alexia\pyhton\data\raw\p4ds_cadenas_unificadas_2025.csv"
df = pd.read_csv(ruta)

# 5 filas para verificar que abrió
df.head()

,Periodo,Grupo,Producto,Super,Precio
0,Abr25,Alimentos y bebidas,Aceite de girasol Marca Propia Envase 900 cc,Devoto,"80,00"
1,Abr25,Alimentos y bebidas,Aceite de girasol Marca Propia Envase 900 cc,Devoto Express,"99,00"
2,Abr25,Alimentos y bebidas,Aceite de girasol Marca Propia Envase 900 cc,Disco,"99,00"
3,Abr25,Alimentos y bebidas,Aceite de girasol Marca Propia Envase 900 cc,Ta - Ta,"95,00"
4,Abr25,Alimentos y bebidas,Aceite de girasol Marca Propia Envase 900 cc,Tienda Inglesa,"97,00"

In [3]:
# cambio el nombre
datos_cadena = pd.read_csv(ruta)

In [4]:
# PASO 3: ANÁLISIS DESCRIPTIVO

# dimensiones (Filas, Columnas)
print("Dimensiones de la tabla (Filas, Columnas):")
print(datos_cadena.shape)
print("-" * 50)

# información sobre tipos de datos y valores no nulos
print("Información general de las columnas:")
datos_cadena.info()
print("-" * 50)

# Resumen estadístico de los precios
print("Resumen estadístico de la columna Precio:")
datos_cadena.describe().T

Dimensiones de la tabla (Filas, Columnas):
(26834, 5)
--------------------------------------------------
Información general de las columnas:
<class 'pandas.DataFrame'>
RangeIndex: 26834 entries, 0 to 26833
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Periodo   26834 non-null  str
 1   Grupo     26671 non-null  str
 2   Producto  26812 non-null  str
 3   Super     24237 non-null  str
 4   Precio    26401 non-null  str
dtypes: str(5)
memory usage: 3.0 MB
--------------------------------------------------
Resumen estadístico de la columna Precio:

          count unique                                    top   freq
Periodo   26834     12                                  Dic25   2333
Grupo     26671     10                    Alimentos y bebidas  13261
Producto  26812    427  Jabón de tocador Dove Blanco, 90 grs.    209
Super     24237     17                             Red Expres   2260
Precio    26401   2234                                  75,00    334

> ### Observaciones:
>
>Conclusiones fundamentales antes de la limpieza:
>
> - **Volumen del Dataset:** **26.834 filas** (que representan registros individuales de relevamientos de precios) y **5 columnas** de análisis (`Periodo`, `Grupo`, `Producto`, `Super` y `Precio`).
> - **Análisis de Valores Nulos:** >   - La variable `Super` es la que presenta mayor cantidad de espacios vacios, con **2.597 valores nulos** (26.834 menos 24.237).
>   - La variable `Precio` (objetivo a analizar) cuenta con **433 valores nulos**, representan pérdidas de información crítica que deberemos mitigar.
>   - Las variables `Grupo` y `Producto` presentan nulos en una escala mucho más reducida (**163** y **22** valores faltantes respectivamente).
> - **Tipos de Datos Corruptos:** El sistema identifica la totalidad de las variables con el tipo de dato `str` (texto). Esto incluye a la columna `Precio`, Generando incoherencia matemática temporal que nos impide obtener un resumen estadístico numérico preliminar.

### Limpieza de datos: Tratar valores nulos (Faltantes)

Analizo cada variable:
- **Variable Objetivo (`Precio`):** Al ser la clase principal a analizar, las filas que no tengan precio no sirven para el análisis ni para los gráficos,las elimino de forma física.
- **Variables Categóricas (`Super`, `Grupo`, `Producto`):** Uso la sustitución, rellenando los espacios vacíos con la etiqueta de texto `'Desconocido'`.

In [5]:
# PASO 4 (CONTINUACIÓN): TRATAMIENTO DE VALORES NULOS

# Elimino filas en donde el precio aparezca como nulo (Target)
datos_cadena = datos_cadena.dropna(subset=['Precio'])

# Rellenamos los nulos de las demás columnas con un valor genérico
datos_cadena['Super'] = datos_cadena['Super'].fillna('Desconocido')
datos_cadena['Grupo'] = datos_cadena['Grupo'].fillna('Desconocido')
datos_cadena['Producto'] = datos_cadena['Producto'].fillna('Desconocido')

print("Verificación final de valores nulos por columna:")
print(datos_cadena.isnull().sum())
print("-" * 50)

print("Dimensiones definitivas del dataset limpio:")
print(datos_cadena.shape)

Verificación final de valores nulos por columna:
Periodo     0
Grupo       0
Producto    0
Super       0
Precio      0
dtype: int64
--------------------------------------------------
Dimensiones definitivas del dataset limpio:
(26401, 5)

In [6]:
# FINAL DE FASE 1: EXPORTACIÓN DEL DATASET LIMPIO

# Guardo tabla en la carpeta de datos procesados
# Usamos index=False para que Pandas no cree una columna extra con los números de fila
ruta_salida = r"C:\Users\aleva\OneDrive\Escritorio\Alexia\pyhton\data\processed\p4ds_cadenas_limpio_2025.csv"

datos_cadena.to_csv(ruta_salida, index=False)

print("¡Fase 1 Completada con éxito!")
print("El archivo limpio ha sido exportado correctamente en data/processed.")
print("-" * 50)

¡Fase 1 Completada con éxito!
El archivo limpio ha sido exportado correctamente en data/processed.
--------------------------------------------------

### Fin de la Fase 1

El dataset ha sido depurado y exportado a la ruta `data/processed/p4ds_cadenas_limpio_2025.csv`. Se garantiza la integridad de los datos para las fases posteriores de análisis descriptivo profundo y visualización de precios.